# Generated by Django 3.2.6 on 2021-08-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210826_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about', 'verbose_name_plural': 'about'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='location',
        ),
        migrations.RemoveField(
            model_name='about',
            name='message',
        ),
    ]
