# Generated by Django 3.2.6 on 2021-08-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
